### ISSUE TITLE
allow passing in lists that autoconvert to json internally

### ISSUE THREAD

**Issue by sckott** [sckott/sofa#24]

**Comment by andrewcstewart** [comment]
+1

**Comment by sckott** [comment]
@andrewcstewart cool, should be able to add this easily, will try to do soon

**Comment by sckott** [comment]
@andrewcstewart okay, added ability to pass in lists now for `doc_create()` and `doc_update()` - a few examples are at the bottom of `doc_create()`.  Let me know if you have any feedback on this.

**Comment by andrewcstewart** [comment]
I just tested this and can confirm.  Works great!

**Comment by sckott** [comment]
:+1:   - closing then
