### ISSUE TITLE
Can cushions not use remote hosts?

### ISSUE THREAD

**Issue by andrewcstewart** [sckott/sofa#25]
I only see options for localhost, cloudant, and iriscouch.  How does one specify one's own couchdb on a remote host?

**Comment by sckott** [comment]
@andrewcstewart right, i hadn't got that far yet, just played with localhost, iriscouch and cloudant

just a sec...

**Comment by sckott** [comment]
installing a remote couch to test this

**Comment by sckott** [comment]
@andrewcstewart okay, try again after re-installing

```r
devtools::install_github("sckott/sofa")
library("sofa")
```

then, e.g. this works from a remote couch i just put up on a digital ocean box

```r
library("sofa")
cushion("oceancouch", base="http://104.236.176.205", port=5984)
alldocs("oceancouch", "beard")
#>          id       key                                rev
#> 1  goodbeer  goodbeer 1-eead79d396ed1d212d4700c6d0af9bf6
#> 2 goodbeers goodbeers 1-eead79d396ed1d212d4700c6d0af9bf6
```

**Comment by andrewcstewart** [comment]
Cool, works perfectly.  Thanks @sckott!

**Comment by sckott** [comment]
great!
